version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql-people:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - 9000:9000
    depends_on:
      - db
    
  nginx:
    container_name: nginx
    build: 
      context: nginx
    ports:
      - 8080:80
    depends_on:
      - app
    networks:
      - node-network


networks:
  node-network:
    driver: bridge
